# Generated by Django 6.0.3 on 2026-05-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_ramen',
            field=models.IntegerField(default=0),
        ),
    ]
