# Generated by Django 6.0.3 on 2026-04-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='grade',
            field=models.CharField(default='F', max_length=2),
        ),
    ]
