# Generated by Django 6.0.3 on 2026-05-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tag_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='post',
        ),
    ]
